version: "3.7"
services:
  system:
    container_name: system
    build: 
      context: ./system/
      dockerfile: Dockerfile
    ports:
      - "9043:9043"
      - "9443:9443"
      - "9464:9464"
    environment:
      - OTEL_SERVICE_NAME=system
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - "jaeger"
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true